- updated fwupd workflows (patching only the latest, master has changed   for bookworm compatibility, read comment in   .github/workflows/fwupd.yml for more info); - updated ffmpeg mirror to the github one (the main mirror is   unavailable); - disabled vte master testing (c++ features that are not available on   debian bookworm), and minor change to verify the linkage against   gnutls-wolfssl; - updated dependencies in the rsyslog (new ones were added upstream in   the master branch); - removed master branch from the matrix of the gst workflow (now   requires gstreamer to be on 1.28.x, we are focused on 1.26.x)

diff --git a/.github/workflows/libvte.yml b/.github/workflows/libvte.yml
--- a/.github/workflows/libvte.yml
+++ b/.github/workflows/libvte.yml
@@ -17,7 +17,7 @@ jobs:
     strategy:
       matrix:
         os: [ ubuntu-latest ]
-        vte_ref: [ 'master', '0.70.6']
+        vte_ref: [ '0.70.6' ]
       fail-fast: false
     runs-on: ${{ matrix.os }}
     container:
@@ -92,12 +92,12 @@ jobs:
       - name: Verify VTE is linked against the custom GnuTLS
         working-directory: vte/_build
         run: |
-          lib=$(find src -maxdepth 1 -name 'libvte-2.91*.so*' | head -n 1)
+          lib=$(find src -maxdepth 1 -type f -name 'libvte-2.91*.so*' | head -n 1)
           echo "Checking linkage for $lib"
           ldd "$lib" | grep gnutls
           if ! ldd "$lib" | grep -q '/opt/gnutls/lib/libgnutls.so'; then
-          echo "::error::VTE is NOT linked against /opt/gnutls/lib/libgnutls.so"
-          exit 1
+            echo "::error::VTE is NOT linked against /opt/gnutls/lib/libgnutls.so"
+            exit 1
           fi
 
       - name: Test VTE build
